
  create table "public"."newsletter" (
    "id" bigint generated by default as identity not null,
    "email" text not null default ''::text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."newsletter" enable row level security;

CREATE UNIQUE INDEX newsletter_email_key ON public.newsletter USING btree (email);

CREATE UNIQUE INDEX newsletter_pkey ON public.newsletter USING btree (id);

alter table "public"."newsletter" add constraint "newsletter_pkey" PRIMARY KEY using index "newsletter_pkey";

alter table "public"."newsletter" add constraint "newsletter_email_key" UNIQUE using index "newsletter_email_key";

grant delete on table "public"."newsletter" to "anon";

grant insert on table "public"."newsletter" to "anon";

grant references on table "public"."newsletter" to "anon";

grant select on table "public"."newsletter" to "anon";

grant trigger on table "public"."newsletter" to "anon";

grant truncate on table "public"."newsletter" to "anon";

grant update on table "public"."newsletter" to "anon";

grant delete on table "public"."newsletter" to "authenticated";

grant insert on table "public"."newsletter" to "authenticated";

grant references on table "public"."newsletter" to "authenticated";

grant select on table "public"."newsletter" to "authenticated";

grant trigger on table "public"."newsletter" to "authenticated";

grant truncate on table "public"."newsletter" to "authenticated";

grant update on table "public"."newsletter" to "authenticated";

grant delete on table "public"."newsletter" to "postgres";

grant insert on table "public"."newsletter" to "postgres";

grant references on table "public"."newsletter" to "postgres";

grant select on table "public"."newsletter" to "postgres";

grant trigger on table "public"."newsletter" to "postgres";

grant truncate on table "public"."newsletter" to "postgres";

grant update on table "public"."newsletter" to "postgres";

grant delete on table "public"."newsletter" to "service_role";

grant insert on table "public"."newsletter" to "service_role";

grant references on table "public"."newsletter" to "service_role";

grant select on table "public"."newsletter" to "service_role";

grant trigger on table "public"."newsletter" to "service_role";

grant truncate on table "public"."newsletter" to "service_role";

grant update on table "public"."newsletter" to "service_role";

grant delete on table "public"."posts" to "postgres";

grant insert on table "public"."posts" to "postgres";

grant references on table "public"."posts" to "postgres";

grant select on table "public"."posts" to "postgres";

grant trigger on table "public"."posts" to "postgres";

grant truncate on table "public"."posts" to "postgres";

grant update on table "public"."posts" to "postgres";


  create policy "newsletter"
  on "public"."newsletter"
  as permissive
  for insert
  to public
with check (true);



